[versions]
client-snyk = "0.1.1"
clikt = "5.0.+"
junit = "5.9.+"
kotlin = "2.2.+"
kotlinx-coroutines = "1.9.+"
logback = "1.5.18"

[plugins]
kotlin-plugin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
client-snyk = { group = "dev.samoylenko", name = "client-snyk", version.ref = "client-snyk" }
clikt = { group = "com.github.ajalt.clikt", name = "clikt", version.ref = "clikt" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
